version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - ./wait-for:/usr/src/app/wait-for
    command: >
      sh -c "
        ./wait-for db:5432 --timeout=30 &&
        npm run migration:run &&
        npm start
      "
    image: gshuo/atm-backend:1.0.0
    container_name: atm-backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
  db:
    image: postgres:13
    container_name: atm-backend-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - atm-db-data:/var/lib/postgresql/data

volumes:
  atm-db-data:
